<template>
    <div className="出行方式">
      <h2>出行方式占比</h2>
      <table>
        <thead>
        <tr>
          <th>年份</th><th>地铁</th><th>步行</th><th>汽车</th><th>公交车</th>
          <th>网约车</th><th>单车</th><th>其他</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>2019</td><td>50%</td><td>12%</td><td>8%</td><td>20%</td><td>4%</td><td>5%</td><td>1%</td>
        </tr>
        <tr>
           <td>2020</td><td>49%</td><td>11%</td><td>9%</td><td>20%</td><td>4%</td><td>4%</td><td>1%</td>
        </tr>
        <tr>
          <td>2021</td><td>48%</td><td>11%</td><td>10%</td><td>20%</td><td>5%</td><td>3%</td><td>1%</td>
        </tr>
        </tbody>
      </table>
    </div>
</template>